"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rjpe7(p6%r&4^#av6=r8)4xbiy#7k$)*qzc%93!-)qs53=7njf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']

# Custom error pages
handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 添加Django REST Framework及其JWT认证模块
    'rest_framework',
    'rest_framework_simplejwt',

    # 自定义项目应用
    'djoser',
    'project'
]

AUTH_USER_MODEL = 'project.User'

# Django REST Framework配置
REST_FRAMEWORK = {
    # 设置默认的认证类，这里使用了JWTAuthentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 设置默认的权限类，这里要求用户必须已认证
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # 设置默认的分页类，这里使用了PageNumberPagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 设置每页显示的条目数量
    'PAGE_SIZE': 10,
}

# JWT Token配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Access Token 有效期 60分钟
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh Token 有效期 7天
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# DJOSER配置
DJOSER = {
    # 设置登录字段为email
    'LOGIN_FIELD': 'email',
    # 要求用户在创建密码时重新输入一次密码
    'USER_CREATE_PASSWORD_RETYPE': True,
    # 要求用户在重置密码时重新输入一次新密码
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    # 启用JWT认证
    'JWT_AUTH': True,
    # 不发送激活邮件
    'SEND_ACTIVATION_EMAIL': False,
    # 设置激活URL的格式
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    # 设置社交认证的Token策略
    'SOCIAL_AUTH_TOKEN_STRATEGY': 'djoser.social.token.jwt.TokenStrategy',
    # 设置密码重置确认URL的格式
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    # 设置用户名重置确认URL的格式
    'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    # 在密码重置确认时显示电子邮件未找到的消息
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
    # 在用户名重置确认时显示电子邮件未找到的消息
    'USERNAME_RESET_SHOW_EMAIL_NOT_FOUND': True,
    # 不使用自定义的Token模型
    'TOKEN_MODEL': None,
    # 自定义序列化器
    'SERIALIZERS': {},
    # 自定义电子邮件设置
    'EMAIL': {},
    # 自定义权限设置
    'PERMISSIONS': {},
}

MIDDLEWARE = [
    # 安全中间件，处理安全相关的HTTP头
    'django.middleware.security.SecurityMiddleware',
    # 会话中间件，处理会话管理
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 认证中间件，处理用户认证
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 消息中间件，处理一次性消息
    'django.contrib.messages.middleware.MessageMiddleware',
    # 常用中间件，处理通用的HTTP头
    'django.middleware.common.CommonMiddleware',
    # CSRF保护中间件，防止跨站请求伪造攻击
    'django.middleware.csrf.CsrfViewMiddleware',
    # 其他中间件...
]
# 配置邮箱
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 示例使用QQ邮箱SMTP服务器 - 请根据实际情况修改
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = '***@qq.com'  # 替换为你的邮箱地址
EMAIL_HOST_PASSWORD = '******'  # 替换为你的邮箱密码或授权码
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True  # QQ邮箱需要使用SSL
DEFAULT_FROM_EMAIL = '来自一个学习的路人'  # 默认发件人

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  
        'NAME': 'myproject',     
        'USER': 'root',         
        'PASSWORD': '123456',   
        'HOST': 'localhost',              
        'PORT': '3306',                      
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'templates' / 'css', BASE_DIR / 'templates' / 'js']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
