# Generated by Django 6.0.2 on 2026-03-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', '普通用户'), ('vip', 'VIP用户'), ('admin', '管理员')], default='normal', max_length=20, verbose_name='用户角色'),
        ),
    ]
